### ISSUE TITLE
Update GitHub Action to build Image from Dockerfile

### ISSUE THREAD

**Issue by raviknox** [accuknox/accuknox-jobs#24]
**Context:**
 - Currently, we're using the docker image `accuknox/accuknox-job:latest`  which was initially created from this [Dockerfile](https://github.com/accuknox/accuknox-jobs/blob/main/Dockerfile) using manual process.
 - This is being used in [**AccuKnox CIS K8s Job**](https://github.com/accuknox/accuknox-jobs/blob/main/cis-k8s-job/templates/cis-job.yaml#L14)

**Problem Statement:**
 - We've updated the content of the Dockerfile and image is still pointing to the old build image, since it is not automated.
 - Hence it'll throw an error as follows
```sh
Defaulted container "cis-k8s-cronjob" out of: cis-k8s-cronjob, kube-bench (init)
entrypoint.sh: 1: Syntax error: redirection unexpected
```

**Comment by raviknox** [comment]
For the time being, manually pushed image on docker hub
 - Image: `accuknox/accuknox-job:latest`
 - Digest: `sha256:0cb25cb05eda6d4cf571c66b7d7c3a9a80b62d74e8de0221dea8c131ad210579`

**Comment by DelusionalOptimist** [comment]
Fixed in https://github.com/accuknox/accuknox-jobs/pull/51
